name = "RidoKeys"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "Rido public keys, to trust Rido software"
tags = ["blog", "certs"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
    name = "rido"
    homepage = "http://rido.site"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"